@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Sep 29 18:46:57 +0900 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_PE_Array_behav -key {Behavioral:sim_1:Functional:tb_PE_Array} -tclbatch tb_PE_Array.tcl -view E:/CCDC/PE_5x5_test - 복사본/tb_PE_Array_behav1.wcfg -log simulate.log"
call xsim  tb_PE_Array_behav -key {Behavioral:sim_1:Functional:tb_PE_Array} -tclbatch tb_PE_Array.tcl -view E:/CCDC/PE_5x5_test - 복사본/tb_PE_Array_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
