webtalk_init -webtalk_dir E:/Verilog/soc/lab03/lab03_2/lab03_2.sim/sim_1/behav/xsim/xsim.dir/tb_PWM_System_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct  9 14:20:39 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cb2330f5-4a84-4d2c-99c6-63e76c27083e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "700e5b5c7ee344c2a3eec650eaa59f83" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "6000320 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.70_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14728_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2327141941 -regid "" -xml E:/Verilog/soc/lab03/lab03_2/lab03_2.sim/sim_1/behav/xsim/xsim.dir/tb_PWM_System_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Verilog/soc/lab03/lab03_2/lab03_2.sim/sim_1/behav/xsim/xsim.dir/tb_PWM_System_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Verilog/soc/lab03/lab03_2/lab03_2.sim/sim_1/behav/xsim/xsim.dir/tb_PWM_System_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
