@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Oct 13 19:00:54 +0900 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_FC_layer_behav -key {Behavioral:sim_1:Functional:tb_FC_layer} -tclbatch tb_FC_layer.tcl -view E:/Verilog/KNU_CCDC-Integrate/KNU_CCDC-Integrate/KNU_CCDC/KNU_CNN.srcs/sim_1/imports/PE_5x5_test_row2/tb_PE_Array_behav1.wcfg -view E:/Verilog/KNU_CCDC-Integrate/KNU_CCDC-Integrate/KNU_CCDC/tb_acc_behav.wcfg -view E:/Verilog/KNU_CCDC-Integrate/KNU_CCDC-Integrate/KNU_CCDC/tb_FC_layer_behav.wcfg -log simulate.log"
call xsim  tb_FC_layer_behav -key {Behavioral:sim_1:Functional:tb_FC_layer} -tclbatch tb_FC_layer.tcl -view E:/Verilog/KNU_CCDC-Integrate/KNU_CCDC-Integrate/KNU_CCDC/KNU_CNN.srcs/sim_1/imports/PE_5x5_test_row2/tb_PE_Array_behav1.wcfg -view E:/Verilog/KNU_CCDC-Integrate/KNU_CCDC-Integrate/KNU_CCDC/tb_acc_behav.wcfg -view E:/Verilog/KNU_CCDC-Integrate/KNU_CCDC-Integrate/KNU_CCDC/tb_FC_layer_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
